import Header from '../../components/Header/Header'
import Hero from '../../components/Hero/Hero'
import About from '../../components/About/About'
import Experience from '../../components/Experience/Experience'
import MenuShowcase from '../../components/MenuShowcase/MenuShowcase'
import Gallery from '../../components/Gallery/Gallery'
import InstagramSection from '../../components/InstagramSection/InstagramSection'
import FinalCTA from '../../components/FinalCTA/FinalCTA'
import Footer from '../../components/Footer/Footer'
export default function Home(){return <><Header/><main><Hero/><About/><Experience/><MenuShowcase/><Gallery/><InstagramSection/><FinalCTA/></main><Footer/></>}
